-- LOTCOW
DROP TRIGGER IF EXISTS INSERT_LOTCOW;
DELIMITER ;;
CREATE TRIGGER INSERT_LOTCOW 
BEFORE INSERT
ON lotcow FOR EACH ROW 
BEGIN 
	UPDATE lot l SET l.cow_amount = l.cow_amount + 1
	WHERE l.id_lot = NEW.id_lot;
END;;
DELIMITER ;

DROP TRIGGER IF EXISTS DELETE_LOTCOW;
DELIMITER ;;
CREATE TRIGGER DELETE_LOTCOW 
AFTER DELETE
ON lotcow FOR EACH ROW
BEGIN 
	UPDATE lot l SET l.cow_amount = l.cow_amount - 1
	WHERE l.id_lot = OLD.id_lot;
END;;
DELIMITER ;