-- LOTCOW
DROP TRIGGER IF EXISTS INSERT_LOTCOW;
DELIMITER ;;
CREATE TRIGGER INSERT_LOTCOW 
BEFORE INSERT
ON lotcow FOR EACH ROW 
BEGIN 
	UPDATE lot l SET l.cow_amount = l.cow_amount + 1
	WHERE l.id_lot = NEW.id_lot;
END;;
DELIMITER ;

DROP TRIGGER IF EXISTS DELETE_LOTCOW;
DELIMITER ;;
CREATE TRIGGER DELETE_LOTCOW 
AFTER DELETE
ON lotcow FOR EACH ROW
BEGIN 
	UPDATE lot l SET l.cow_amount = l.cow_amount - 1
	WHERE l.id_lot = OLD.id_lot;
END;;
DELIMITER ;

DROP TRIGGER IF EXISTS VALIDATE_ML_UPDATE;
DELIMITER ;;
CREATE TRIGGER VALIDATE_ML_UPDATE 
BEFORE UPDATE
ON cowvaccine FOR EACH ROW
BEGIN 
	UPDATE inventory i SET i.ml = (i.ml-(NEW.ml - OLD.ml))
	WHERE i.id_vaccine = id_vaccine;
END;;
DELIMITER ;

DROP TRIGGER IF EXISTS VALIDATE_ML_INSERT;
DELIMITER ;;
CREATE TRIGGER VALIDATE_ML_INSERT 
BEFORE INSERT
ON cowvaccine FOR EACH ROW
BEGIN 
	UPDATE inventory i SET i.ml = (i.ml-(NEW.ml - OLD.ml))
	WHERE i.id_vaccine = id_vaccine;
END;;
DELIMITER ;